/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdateCanWithdraw
 * @category generated
 */
export type UpdateCanWithdrawInstructionArgs = {
  canClaim: boolean
  productId: string
  escrowBump: number
}
/**
 * @category Instructions
 * @category UpdateCanWithdraw
 * @category generated
 */
export const updateCanWithdrawStruct = new beet.FixableBeetArgsStruct<
  UpdateCanWithdrawInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['canClaim', beet.bool],
    ['productId', beet.utf8String],
    ['escrowBump', beet.u8],
  ],
  'UpdateCanWithdrawInstructionArgs'
)
/**
 * Accounts required by the _updateCanWithdraw_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [] seller
 * @property [] buyer
 * @property [] escrow
 * @category Instructions
 * @category UpdateCanWithdraw
 * @category generated
 */
export type UpdateCanWithdrawInstructionAccounts = {
  authority: web3.PublicKey
  seller: web3.PublicKey
  buyer: web3.PublicKey
  escrow: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateCanWithdrawInstructionDiscriminator = [
  244, 194, 158, 208, 67, 204, 126, 225,
]

/**
 * Creates a _UpdateCanWithdraw_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateCanWithdraw
 * @category generated
 */
export function createUpdateCanWithdrawInstruction(
  accounts: UpdateCanWithdrawInstructionAccounts,
  args: UpdateCanWithdrawInstructionArgs,
  programId = new web3.PublicKey('6PzCGqfvD4warUKFqyB2GUgdw3U4QM9dzrK7rkj9ooB9')
) {
  const [data] = updateCanWithdrawStruct.serialize({
    instructionDiscriminator: updateCanWithdrawInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.seller,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyer,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.escrow,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
