/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdateCanClaim
 * @category generated
 */
export type UpdateCanClaimInstructionArgs = {
  productId: string
  escrowBump: number
}
/**
 * @category Instructions
 * @category UpdateCanClaim
 * @category generated
 */
export const updateCanClaimStruct = new beet.FixableBeetArgsStruct<
  UpdateCanClaimInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['productId', beet.utf8String],
    ['escrowBump', beet.u8],
  ],
  'UpdateCanClaimInstructionArgs'
)
/**
 * Accounts required by the _updateCanClaim_ instruction
 *
 * @property [] seller
 * @property [_writable_, **signer**] buyer
 * @property [] escrow
 * @category Instructions
 * @category UpdateCanClaim
 * @category generated
 */
export type UpdateCanClaimInstructionAccounts = {
  seller: web3.PublicKey
  buyer: web3.PublicKey
  escrow: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateCanClaimInstructionDiscriminator = [
  116, 25, 112, 41, 160, 206, 130, 121,
]

/**
 * Creates a _UpdateCanClaim_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateCanClaim
 * @category generated
 */
export function createUpdateCanClaimInstruction(
  accounts: UpdateCanClaimInstructionAccounts,
  args: UpdateCanClaimInstructionArgs,
  programId = new web3.PublicKey('6PzCGqfvD4warUKFqyB2GUgdw3U4QM9dzrK7rkj9ooB9')
) {
  const [data] = updateCanClaimStruct.serialize({
    instructionDiscriminator: updateCanClaimInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.seller,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.escrow,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
